apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-svc-deployment
spec:
  selector:
    matchLabels:
      app: echo-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-svc
    spec:
      containers:
      - name: echo-svc
        image: echo-svc:v1
        ports:
        - containerPort: 3001

